<?php
/**
 * @file
 */

/**
 * Implements hooks_theme().
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;


/**
 * Implements hook_batch_alter().
 */
function blog_navigation_theme($existing, $type, $theme, $path)
{
  return [
    'blog_navigation' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'blog_navigation.theme.inc'
    ],
  ];
}


/**
 * Implements hook_entity_extra_field_info().
 */
function blog_navigation_entity_extra_field_info()
{
  $extra = [];
  foreach (\Drupal\node\Entity\NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['prev_next'] = [
      'label' => t('buttons to prev end next'),
      'wight' => 100,
      'visible' => FALSE,
    ];
  }
  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function blog_navigation_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode)
{
  if($display->getComponent('prev_next')){
    $build['prev_next'] = [
      '#theme' => 'blog_navigation',
      '#entity'=> $entity,
    ];
  }

}
